local _, ns = ...
ns.items = ns.items or {}

-- [ Expansion 11: The War Within - Sorted by ID (Newest First) ]

ns.items[264675] = "Cache from the Infinite's Armory"                -- from AutoOpenContainers
ns.items[256763] = "Cache from the Infinite's Armory"                -- Legion Remix
ns.items[255676] = "Phase Diver's Cache"                             -- from AutoOpenContainers
ns.items[254850] = "Minor Bronze Cache"                              -- from AutoOpenContainers
ns.items[254849] = "Minor Bronze Cache"                              -- from AutoOpenContainers
ns.items[254848] = "Minor Bronze Cache"                              -- from AutoOpenContainers
ns.items[254847] = "Minor Bronze Cache"                              -- from AutoOpenContainers
ns.items[254325] = "Worldsoul Satchel"                               -- from AutoOpenContainers
ns.items[254324] = "Worldsoul Satchel"                               -- from AutoOpenContainers
ns.items[254323] = "Worldsoul Satchel"                               -- from AutoOpenContainers
ns.items[253357] = "Felscorned Arsenal"                              -- Legion Remix from AutoOpenContainers
ns.items[251821] = "Cache of Infinite Power"                         -- Legion Remix
ns.items[250769] = "The Weaver's Gratuity"                           -- from OpenableBeGone
ns.items[250768] = "The Vizier's Capital"                            -- from OpenableBeGone
ns.items[250767] = "The General's War Chest"                         -- from OpenableBeGone
ns.items[250766] = "Radiant Cache"                                   -- from OpenableBeGone
ns.items[250765] = "Awakened Mechanical Cache"                       -- from OpenableBeGone
ns.items[250764] = "Nanny's Surge Dividends"                         -- from OpenableBeGone
ns.items[250763] = "Theater Troupe's Trove"                          -- from OpenableBeGone
ns.items[249714] = "Timewarped Mission Supplies"                     -- Legion Remix from AutoOpenContainers
ns.items[248247] = "Cache of Infinite Power"                         -- Legion Remix
ns.items[248127] = "Delver's Cosmetic Surprise Bag"
ns.items[248126] = "Delver's Starter Kit"
ns.items[247821] = "Cache of K'areshi Treasures"
ns.items[247820] = "Cache of K'areshi Treasures (Heroic)"
ns.items[246815] = "Lesser Bronze Cache"                             -- Legion Remix
ns.items[246814] = "Bronze Cache"                                    -- Legion Remix
ns.items[246813] = "Greater Bronze Cache"                            -- Legion Remix
ns.items[246812] = "Minor Bronze Cache"                              -- Legion Remix
ns.items[246697] = "Self-Assembling Homeware Kit"                    -- from AutoOpenContainers
ns.items[245611] = "Wriggling Pinnacle Cache"
ns.items[245589] = "Hellcaller Chest"
ns.items[245553] = "Heroic Cache of Infinite Treasure"               -- Legion Remix
ns.items[245280] = "Seasoned Khaz Algar Adventurer's Cache"          -- from OpenableBeGone
ns.items[244883] = "Seasoned Undermine Adventurer's Cache"           -- from OpenableBeGone
ns.items[244865] = "Pinnacle Cache"
ns.items[244842] = "Fabled Veteran's Cache"
ns.items[244696] = "Overcharged Chest"
ns.items[244466] = "Dagran's Pouch of Shards"
ns.items[244457] = "Keystone Container"                              -- from AutoOpenContainers
ns.items[244336] = "K'aresh Box of Resonance Crystals"               -- from OpenableBeGone
ns.items[244335] = "K'aresh Box of Valorstones"                      -- from OpenableBeGone
ns.items[243373] = "Timerunner's Weaponry"                           -- Legion Remix
ns.items[243235] = "Adventurer's Footlocker"
ns.items[242386] = "Lorewalker's Crate of Memorabilia"
ns.items[240208] = "Void-Touched Valorstone"                         -- from AutoOpenContainers
ns.items[240207] = "Golden Valorstone"                               -- from AutoOpenContainers
ns.items[240175] = "Crystallized Ethereal Voidsplinter"              -- from AutoOpenContainers
ns.items[239594] = "Crimson Valorstone"                              -- from AutoOpenContainers
ns.items[239546] = "Confiscated Cultist's Bag"
ns.items[239489] = "Radiant Officer's Cache"
ns.items[239440] = "Dastardly Prize Purse"
ns.items[239303] = "Cache of Infinite Treasure"                      -- from AutoOpenContainers
ns.items[239224] = "Cache of Infinite Treasure"                      -- from AutoOpenContainers
ns.items[239128] = "Theatre Troupe's Trove"
ns.items[239126] = "Radiant Cache"                                   -- from OpenableBeGone
ns.items[239125] = "The Weaver's Gratuity"                           -- from OpenableBeGone
ns.items[239124] = "The Vizier's Capital"                            -- from OpenableBeGone
ns.items[239122] = "The General's War Chest"
ns.items[239121] = "Awakened Mechanical Cache"                       -- from OpenableBeGone
ns.items[239120] = "Seasoned Adventurer's Cache"                     -- from OpenableBeGone
ns.items[239118] = "Pinnacle Cache"
ns.items[239004] = "Radiant Service Satchel"
ns.items[238208] = "Nanny's Surge Dividends"
ns.items[238207] = "Nanny's Surge Dividends"                         -- from OpenableBeGone
ns.items[237812] = "Cache of Infinite Treasure"                      -- Legion Remix
ns.items[237760] = "Arathi Champion's Spoils"
ns.items[237759] = "Arathi Cleric's Chest"
ns.items[237743] = "Arathi Soldier's Coffer"
ns.items[237135] = "Blackwater Trove"                                -- from AutoOpenContainers
ns.items[237134] = "Steamwheedle Trove"                              -- from AutoOpenContainers
ns.items[237133] = "Venture Co. Trove"                               -- from AutoOpenContainers
ns.items[237132] = "Bilgewater Trove"                                -- from AutoOpenContainers
ns.items[236954] = "Void-Touched Valorstone"                         -- from AutoOpenContainers
ns.items[236953] = "Crimson Valorstone"
ns.items[236944] = "Weathered Mysterious Satchel"
ns.items[236877] = "Crystallized Essence of Kaja'mite"               -- from AutoOpenContainers
ns.items[236758] = "Extravagant Tip Chest"
ns.items[236757] = "Generous Tip Chest"
ns.items[236756] = "Socially Expected Tip Chest"                     -- from AutoOpenContainers
ns.items[236632] = "Pouch of Voidbane Gems"                          -- from AutoOpenContainers
ns.items[235911] = "Weathered Mysterious Satchel"
ns.items[235639] = "Seasoned Adventurer's Cache"                     -- from AutoOpenContainers
ns.items[235631] = "[NOT USED] Mysterious Large Satchel of Goodies"  -- from AutoOpenContainers
ns.items[235610] = "Seasoned Adventurer's Cache"                     -- from AutoOpenContainers
ns.items[235558] = "Box of Darkfuse Miscellany"                      -- from AutoOpenContainers
ns.items[235548] = "Earthen Landlubber's Cache"                      -- from AutoOpenContainers
ns.items[235265] = "Venture Co.'s Trove"                             -- from AutoOpenContainers
ns.items[235264] = "Venture Co.'s Trove"                             -- from AutoOpenContainers
ns.items[235263] = "Steamwheedle's Trove"                            -- from AutoOpenContainers
ns.items[235262] = "Steamwheedle's Trove"                            -- from AutoOpenContainers
ns.items[235261] = "Blackwater's Trove"                              -- from AutoOpenContainers
ns.items[235260] = "Blackwater's Trove"                              -- from AutoOpenContainers
ns.items[235259] = "Bilgewater's Trove"                              -- from AutoOpenContainers
ns.items[235258] = "Bilgewater's Trove"                              -- from AutoOpenContainers
ns.items[235151] = "Distinguished Actor's Chest"
ns.items[235054] = "Pristine Mysterious Cache"
ns.items[235052] = "Weathered Mysterious Cache"
ns.items[234816] = "Overflowing Bag of Iron"                         -- from AutoOpenContainers
ns.items[234746] = "Venture Co.'s Trove"                             -- from AutoOpenContainers
ns.items[234745] = "Bilgewater's Trove"                              -- from AutoOpenContainers
ns.items[234744] = "Blackwater's Trove"                              -- from AutoOpenContainers
ns.items[234743] = "Steamwheedle's Trove"                            -- from AutoOpenContainers
ns.items[234731] = "Cache of Undermine Treasures"
ns.items[234729] = "Cache of Undermine Treasures"
ns.items[234450] = "Pirate's Booty"                                  -- from AutoOpenContainers
ns.items[234425] = "Forgotten Folio"                                 -- from AutoOpenContainers
ns.items[234413] = "Satchel of Exotic Mysteries"                     -- from AutoOpenContainers
ns.items[233558] = "S.C.R.A.P. Scrubber Deluxe"                      -- from AutoOpenContainers
ns.items[233557] = "Sifted Pile of Scrap"                            -- from AutoOpenContainers
ns.items[233281] = "Delver's Cosmetic Surprise Bag"                  -- from AutoOpenContainers
ns.items[233276] = "Delver's Starter Kit"
ns.items[232929] = "[DNT] Large Surge Chest"                         -- from AutoOpenContainers
ns.items[232928] = "[DNT] Medium Surge Chest"                        -- from AutoOpenContainers
ns.items[232927] = "[DNT] Small Surge Chest"                         -- from AutoOpenContainers
ns.items[232877] = "Timely Goodie Bag"
ns.items[232631] = "Wrapped Spear"                                   -- from AutoOpenContainers
ns.items[232616] = "Astral Gladiator's Coin Pouch"                   -- from AutoOpenContainers
ns.items[232615] = "Prized Gladiator's Coin Pouch"                   -- from AutoOpenContainers
ns.items[232602] = "Forged Gladiator's Coin Pouch"                   -- from AutoOpenContainers
ns.items[232473] = "Cache of Dark Iron Treasures"                    -- from AutoOpenContainers
ns.items[232472] = "Cache of Dark Iron Treasures"                    -- from AutoOpenContainers
ns.items[232465] = "Darkfuse Trove"                                  -- from AutoOpenContainers
ns.items[232463] = "Overflowing Undermine Trove"                     -- from AutoOpenContainers
ns.items[232382] = "Golden Valorstone"                               -- from AutoOpenContainers
ns.items[232372] = "Crate of Bygone Riches"
ns.items[232076] = "Adventurer's Warbound Battlegear Drop"           -- from AutoOpenContainers
ns.items[230032] = "Overflowing K'aresh Trust Trove"                 -- from AutoOpenContainers
ns.items[229354] = "Algari Adventurer's Cache"
ns.items[229130] = "Cache of Delver's Spoils"                        -- from AutoOpenContainers
ns.items[229129] = "Cache of Delver's Spoils"
ns.items[229006] = "Cache of Earthen Treasures"                      -- from AutoOpenContainers
ns.items[229005] = "Cache of Earthen Treasures"                      -- from AutoOpenContainers
ns.items[228962] = "[DNT]Large Bag of Coffee Beans"                  -- from AutoOpenContainers
ns.items[228961] = "[DNT]Medium Bag of Coffee Beans"                 -- from AutoOpenContainers
ns.items[228960] = "[DNT]Small Bag of Coffee Beans"                  -- from AutoOpenContainers
ns.items[228959] = "Pile of Unidentified Meat"                       -- from AutoOpenContainers
ns.items[228933] = "Algari Leatherworker's Satchel"
ns.items[228932] = "Algari Engineer's Satchel"
ns.items[228931] = "Algari Enchanter's Satchel"                      -- from AutoOpenContainers
ns.items[228920] = "Satchel of Chitin"                               -- from AutoOpenContainers
ns.items[228919] = "Satchel of Algari Herbs"                         -- from AutoOpenContainers
ns.items[228918] = "Satchel of Leather"                              -- from AutoOpenContainers
ns.items[228917] = "Satchel of Ore"
ns.items[228916] = "Algari Tailor's Satchel"
ns.items[228910] = "Cache of Nerubian Treasures"                     -- from AutoOpenContainers
ns.items[228741] = "Lamplighter Supply Satchel"
ns.items[228612] = "Artisan's Consortium Payout"                     -- OpenableBeGone
ns.items[228611] = "Artisan's Consortium Payout"                     -- OpenableBeGone
ns.items[228610] = "Artisan's Consortium Payout"                     -- OpenableBeGone
ns.items[228361] = "Seasoned Adventurer's Cache"                     -- from AutoOpenContainers
ns.items[228337] = "Satchel of Surplus Dust"                         -- from AutoOpenContainers
ns.items[228220] = "Waxy Bundle"
ns.items[227792] = "Everyday Cache"
ns.items[227713] = "Artisan's Consortium Payout"                     -- from AutoOpenContainers
ns.items[227682] = "Satchel of Surplus Cloth"                        -- from AutoOpenContainers
ns.items[227681] = "Satchel of Surplus Leather"                      -- from AutoOpenContainers
ns.items[227680] = "zzOld Do Not Use (DNT)"                          -- from AutoOpenContainers
ns.items[227679] = "zzOld Do Not Use (DNT)"                          -- from AutoOpenContainers
ns.items[227678] = "zzOld Do Not Use (DNT)"                          -- from AutoOpenContainers
ns.items[227677] = "zzOld Do Not Use (DNT)"                          -- from AutoOpenContainers
ns.items[227676] = "Satchel of Surplus Ore"                          -- from AutoOpenContainers
ns.items[227675] = "Satchel of Surplus Herbs"                        -- from AutoOpenContainers
ns.items[227450] = "Sky Racer's Purse"
ns.items[226814] = "Chest of Gold"
ns.items[226813] = "Golden Valorstone"                               -- from AutoOpenContainers
ns.items[226273] = "Awakened Mechanical Cache"
ns.items[226264] = "Radiant Cache"
ns.items[226263] = "Theater Troupe's Trove"                          -- from AutoOpenContainers
ns.items[226256] = "Token of the Remembrancers"
ns.items[226199] = "Silk Kej Purse"                                  -- from AutoOpenContainers
ns.items[226198] = "Resonance Crystal Agglomeration"                 -- from AutoOpenContainers
ns.items[226196] = "Silk Kej Pouch"                                  -- from AutoOpenContainers
ns.items[226195] = "Resonance Crystal Cluster"                       -- from AutoOpenContainers
ns.items[226194] = "Cache of Nerubian Treasures (Heroic)"
ns.items[226193] = "Cache of Nerubian Treasures"
ns.items[226154] = "Wax-Sealed Crafty Crest"                         -- from AutoOpenContainers
ns.items[226153] = "Big Pile of Humming Shinies"                     -- from AutoOpenContainers
ns.items[226152] = "Wax-sealed Crests"                               -- from AutoOpenContainers
ns.items[226151] = "Wax-Coated Coffer Unlocker"                      -- from AutoOpenContainers
ns.items[226150] = "Gem-Studded Candelabra"                          -- from AutoOpenContainers
ns.items[226149] = "Pile of Humming Shinies"
ns.items[226148] = "Wax-sealed Weathered Crests"
ns.items[226147] = "Bunch of Brave Rocks"
ns.items[226146] = "Handful of Humming Shinies"
ns.items[226103] = "The Weaver's Trove"                              -- from AutoOpenContainers
ns.items[226101] = "Chromie's Tour Goodie Bag"                       -- from AutoOpenContainers
ns.items[226100] = "The Vizier's Trove"                              -- from AutoOpenContainers
ns.items[226045] = "The General's Trove"                             -- from AutoOpenContainers
ns.items[225896] = "Void-Touched Valorstone"                         -- from AutoOpenContainers
ns.items[225890] = "Durable Information Securing Container"
ns.items[225881] = "Big Bag of Barter Boulders"                      -- from AutoOpenContainers
ns.items[225739] = "Algari Distinguishment"                          -- from AutoOpenContainers
ns.items[225573] = "The Vizier's Capital"                            -- from AutoOpenContainers
ns.items[225572] = "The General's War Chest"                         -- from AutoOpenContainers
ns.items[225571] = "The Weaver's Gratuity"
ns.items[225247] = "Overflowing Severed Threads Trove"               -- from AutoOpenContainers
ns.items[225246] = "Overflowing Hallowfall Trove"                    -- from AutoOpenContainers
ns.items[225245] = "Overflowing Trove of the Deeps"                  -- from AutoOpenContainers
ns.items[225239] = "Overflowing Council of Dornogal Trove"           -- from AutoOpenContainers
ns.items[225055] = "Memory Cache"
ns.items[224941] = "Radiant Fuel Cache"                              -- from AutoOpenContainers
ns.items[224913] = "Radiant Fuel Cache"                              -- from AutoOpenContainers
ns.items[224726] = "Waxy Box of Rocks"                               -- from AutoOpenContainers
ns.items[224725] = "Waxy Bundle of Herbs"                            -- from AutoOpenContainers
ns.items[224724] = "Waxy Bundle of Dust"                             -- from AutoOpenContainers
ns.items[224723] = "Waxy Bundle of Leather"                          -- from AutoOpenContainers
ns.items[224722] = "Waxy Bundle of Resonance Crystals"               -- from AutoOpenContainers
ns.items[224721] = "Wax-Sealed Box"                                  -- from AutoOpenContainers
ns.items[224650] = "Wax-Sealed Pouch"                                -- from AutoOpenContainers
ns.items[224588] = "Box o' Booms"                                    -- from AutoOpenContainers
ns.items[224587] = "Box o' Booms"                                    -- from AutoOpenContainers
ns.items[224586] = "Box o' Booms"                                    -- from AutoOpenContainers
ns.items[224573] = "Crystal Satchel of Cooperation"                  -- from AutoOpenContainers
ns.items[224557] = "Field Medic's Hazard Payout"                     -- from AutoOpenContainers
ns.items[224556] = "Glorious Contender's Strongbox"
ns.items[224407] = "Radiant Cache"
ns.items[224302] = "Severed Threads Commendation"
ns.items[224301] = "Hallowfall Arathi Commendation"
ns.items[224300] = "Assembly of the Deeps Commendation"
ns.items[224298] = "Council of Dornogal Commendation"
ns.items[224292] = "Theater Troupe's Trove"
ns.items[224291] = "Pinnacle Cache"
ns.items[224156] = "Bottomless Bag of Khaz Algar General Goods"      -- from AutoOpenContainers
ns.items[224100] = "Bottomless Bag of Khaz Algar General Goods"      -- from AutoOpenContainers
ns.items[224040] = "Bottomless Bag of Khaz Algar Optional Goods"     -- from AutoOpenContainers
ns.items[224039] = "Bottomless Bag of Khaz Algar Tailoring Goods"    -- from AutoOpenContainers
ns.items[224037] = "Bottomless Bag of Khaz Algar Leatherworking Goods" -- from AutoOpenContainers
ns.items[224035] = "Bottomless Bag of Khaz Algar Jewelcrafting Goods" -- from AutoOpenContainers
ns.items[224034] = "Bottomless Bag of Khaz Algar Inscription Goods"  -- from AutoOpenContainers
ns.items[224033] = "Bottomless Bag of Khaz Algar Engineering Goods"  -- from AutoOpenContainers
ns.items[224032] = "Bottomless Bag of Khaz Algar Enchanting Goods"   -- from AutoOpenContainers
ns.items[224031] = "Bottomless Bag of Khaz Algar Blacksmithing Goods" -- from AutoOpenContainers
ns.items[224030] = "Bottomless Bag of Khaz Algar Alchemy Goods"      -- from AutoOpenContainers
ns.items[224029] = "Bottomless Bag of Khaz Algar Skins"              -- from AutoOpenContainers
ns.items[224028] = "Bottomless Bag of Khaz Algar Ore"                -- from AutoOpenContainers
ns.items[224027] = "Bottomless Bag of Khaz Algar Herbs"              -- from AutoOpenContainers
ns.items[223953] = "Timerunner's Parting Pack"
ns.items[223622] = "20th Anniversary Cache"                          -- from AutoOpenContainers
ns.items[223621] = "20th Anniversary Cache"                          -- from AutoOpenContainers
ns.items[223620] = "20th Anniversary Cache"                          -- from AutoOpenContainers
ns.items[223619] = "Bronze Celebration Goodie Bag"                   -- from AutoOpenContainers
ns.items[223253] = "Nerubian Offerings"
ns.items[222977] = "Scorched Junk"                                   -- from AutoOpenContainers
ns.items[221863] = "Awakened Mechanical Cache"
ns.items[221503] = "Explorer's Warbound Battlegear Drop"             -- from AutoOpenContainers
ns.items[221502] = "Adventurer's Warbound Battlegear Drop"           -- OpenableBeGone
ns.items[221269] = "Crimson Valorstone"
ns.items[220456] = "Silk-Spun Supplies"
ns.items[218738] = "Bizarrely Shaped Stomach"                        -- from AutoOpenContainers
ns.items[217191] = "Pouch of Radiant Shards"
ns.items[217013] = "Expert Actor's Chest"                            -- from AutoOpenContainers
ns.items[217012] = "Novice Actor's Chest"                            -- from AutoOpenContainers
ns.items[217011] = "Amateur Actor's Chest"
ns.items[216712] = "Pristine Mysterious Cache"
ns.items[215359] = "Very Large Valdrakken Accord Supply Pack"        -- from AutoOpenContainers
ns.items[213793] = "Algari Sapphire Prism"                           -- from AutoOpenContainers
ns.items[213792] = "Algari Sapphire Prism"                           -- from AutoOpenContainers
ns.items[213791] = "Algari Sapphire Prism"                           -- from AutoOpenContainers
ns.items[213790] = "Algari Onyx Prism"                               -- from AutoOpenContainers
ns.items[213789] = "Algari Onyx Prism"                               -- from AutoOpenContainers
ns.items[213788] = "Algari Onyx Prism"                               -- from AutoOpenContainers
ns.items[213787] = "Algari Ruby Prism"                               -- from AutoOpenContainers
ns.items[213786] = "Algari Ruby Prism"                               -- from AutoOpenContainers
ns.items[213785] = "Algari Ruby Prism"                               -- from AutoOpenContainers
ns.items[213784] = "Algari Emerald Prism"                            -- from AutoOpenContainers
ns.items[213783] = "Algari Emerald Prism"                            -- from AutoOpenContainers
ns.items[213782] = "Algari Emerald Prism"                            -- from AutoOpenContainers
ns.items[213781] = "Algari Amber Prism"                              -- from AutoOpenContainers
ns.items[213780] = "Algari Amber Prism"                              -- from AutoOpenContainers
ns.items[213779] = "Algari Amber Prism"                              -- from AutoOpenContainers
ns.items[211112] = "Large Undercoin Satchel"
ns.items[211110] = "Undercoin Satchel"
ns.items[211105] = "Delver's Bounty"
ns.items[210747] = "Concealed Contraband"


