local _, ns = ...
ns.items = ns.items or {}

-- [ Expansion 10: Dragonflight - Sorted by ID (Newest First) ]
ns.items[218130] = "Adventurer's Footlocker"
ns.items[217111] = "Cache of Awakened Dreams"
ns.items[217110] = "Cache of Awakened Embers"
ns.items[217109] = "Cache of Awakened Storms"
ns.items[216638] = "Timerunner's Intro Kit"                          -- from OpenableBeGone
ns.items[215364] = "Cache of Dreams"
ns.items[215363] = "Cache of Embers"
ns.items[215362] = "Cache of Storms"
ns.items[215359] = "Very Large Valdrakken Accord Supply Pack"        -- from OpenableBeGone
ns.items[215160] = "The Big Dig Rig"                                 -- from OpenableBeGone
ns.items[213793] = "Algari Sapphire Prism"                           -- from OpenableBeGone
ns.items[213792] = "Algari Sapphire Prism"                           -- from OpenableBeGone
ns.items[213791] = "Algari Sapphire Prism"                           -- from OpenableBeGone
ns.items[213790] = "Algari Onyx Prism"                               -- from OpenableBeGone
ns.items[213789] = "Algari Onyx Prism"                               -- from OpenableBeGone
ns.items[213788] = "Algari Onyx Prism"                               -- from OpenableBeGone
ns.items[213787] = "Algari Ruby Prism"                               -- from OpenableBeGone
ns.items[213786] = "Algari Ruby Prism"                               -- from OpenableBeGone
ns.items[213785] = "Algari Ruby Prism"                               -- from OpenableBeGone
ns.items[213784] = "Algari Emerald Prism"                            -- from OpenableBeGone
ns.items[213783] = "Algari Emerald Prism"                            -- from OpenableBeGone
ns.items[213782] = "Algari Emerald Prism"                            -- from OpenableBeGone
ns.items[213781] = "Algari Amber Prism"                              -- from OpenableBeGone
ns.items[213780] = "Algari Amber Prism"                              -- from OpenableBeGone
ns.items[213779] = "Algari Amber Prism"                              -- from OpenableBeGone
ns.items[213541] = "Whelpling's Bountiful Chest"                     -- from OpenableBeGone
ns.items[213429] = "Meticulous Archivist's Appendix"
ns.items[213190] = "Preserved Djaradin Tome"
ns.items[213189] = "Preserved Dragonkin Tome"
ns.items[213188] = "Dusty Dracthyr Tome"
ns.items[213187] = "Dusty Drakonid Tome"
ns.items[213186] = "Dusty Niffen Tome"
ns.items[213185] = "Dusty Centaur Tome"
ns.items[213177] = "Immaculate Tome"
ns.items[213176] = "Preserved Isles Tome"
ns.items[213175] = "Dusty Djaradin Tome"
ns.items[212458] = "Awakened Flightstone"                            -- from OpenableBeGone
ns.items[212157] = "An Invitation"                                   -- from OpenableBeGone
ns.items[211430] = "Bundle of Love Tokens"                           -- from OpenableBeGone
ns.items[211429] = "Bundle of Love Tokens"                           -- from OpenableBeGone
ns.items[211414] = "Blossoming Dreamtrove"
ns.items[211413] = "Budding Dreamtrove"
ns.items[211411] = "Sprouting Dreamtrove"
ns.items[211410] = "Bloomed Wilding Cache"
ns.items[211394] = "Harvested Dreamseed Cache"
ns.items[211389] = "Cache of Overblooming Treasures"
ns.items[211388] = "Timerunner's Starter Kit"                        -- from OpenableBeGone
ns.items[211373] = "Bag of Many Wonders"
ns.items[211303] = "Dryad's Supply Pouch"
ns.items[211279] = "Cache of Infinite Treasure"                      -- from OpenableBeGone
ns.items[210992] = "Overflowing Dream Warden Trove"                  -- from OpenableBeGone
ns.items[210991] = "Small Box of Vials"                              -- from OpenableBeGone
ns.items[210872] = "Satchel of Dreams"
ns.items[210760] = "Honorable Satchel of Herbs"                      -- from OpenableBeGone
ns.items[210759] = "Honorable Satchel of Ore"                        -- from OpenableBeGone
ns.items[210758] = "Honorable Satchel of Fabrics"                    -- from OpenableBeGone
ns.items[210726] = "Ruby Flightstone"                                -- from OpenableBeGone
ns.items[210549] = "Dream Racer's Purse"
ns.items[210226] = "Large Emerald Bloom"                             -- from OpenableBeGone
ns.items[210225] = "Medium Emerald Bloom"                            -- from OpenableBeGone
ns.items[210224] = "Small Emerald Bloom"                             -- from OpenableBeGone
ns.items[210219] = "Gigantic Dreamy Bounty"                          -- from OpenableBeGone
ns.items[210218] = "Plump Dreamy Bounty"                             -- from OpenableBeGone
ns.items[210217] = "Small Dreamy Bounty"                             -- from OpenableBeGone
ns.items[210180] = "Emerald Flightstone"                             -- from OpenableBeGone
ns.items[210063] = "Invader's Satchel of Helpful Goods"
ns.items[210062] = "Ironbound Satchel of Helpful Goods"
ns.items[209835] = "Crate of Dreambound Plate"                       -- from OpenableBeGone
ns.items[209834] = "Crate of Dreambound Mail"                        -- from OpenableBeGone
ns.items[209833] = "Crate of Dreambound Armor"                       -- from OpenableBeGone
ns.items[209832] = "Crate of Dreambound Leather"                     -- from OpenableBeGone
ns.items[209831] = "Wyrm's Bountiful Chest"                          -- from OpenableBeGone
ns.items[209037] = "Cache of Amirdrassil Treasures"                  -- from OpenableBeGone
ns.items[209036] = "Cache of Amirdrassil Treasures"                  -- from OpenableBeGone
ns.items[209026] = "Loot-Stuffed Pumpkin"                            -- from OpenableBeGone
ns.items[209025] = "Loot-Filled Pumpkin"                             -- from OpenableBeGone
ns.items[209020] = "Loot-Filled Pumpkin"                             -- from OpenableBeGone
ns.items[208878] = "Adventurer's Footlocker"
ns.items[208691] = "Argunite Cluster"                                -- from OpenableBeGone
ns.items[208390] = "Bronze Archive Stone"                            -- from OpenableBeGone
ns.items[208095] = "Cache of Timewarped Treasures"                   -- from OpenableBeGone
ns.items[208094] = "Cache of Timewarped Treasures"                   -- from OpenableBeGone
ns.items[208091] = "Cache of Timewarped Treasures"                   -- from OpenableBeGone
ns.items[208090] = "Contained Paracausality"
ns.items[208054] = "Mystery Box"
ns.items[208028] = "Knot Thimblejack's Cache"                        -- from OpenableBeGone
ns.items[208015] = "Stuffed Deviate Scale Pouch"                     -- from OpenableBeGone
ns.items[208006] = "Greater Paracausal Chest"                        -- from OpenableBeGone
ns.items[207594] = "Looter's Purse"                                  -- from OpenableBeGone
ns.items[207584] = "Box of Volatile Reality"
ns.items[207583] = "Box of Collapsed Reality"
ns.items[207582] = "Box of Tampered Reality"
ns.items[207096] = "Paracausal Chest"                                -- from OpenableBeGone
ns.items[207094] = "Warmonger's Leather Suit Bag"                    -- from OpenableBeGone
ns.items[207093] = "Jingoist's Mail Suit Bag"                        -- from OpenableBeGone
ns.items[207082] = "Jingoist's Cloth Armor Bag"                      -- from OpenableBeGone
ns.items[207081] = "Warmonger's Cloth Armor Bag"                     -- from OpenableBeGone
ns.items[207080] = "Jingoist's Leather Armor Bag"                    -- from OpenableBeGone
ns.items[207079] = "Warmonger's Leather Armor Bag"                   -- from OpenableBeGone
ns.items[207078] = "Jingoist's Mail Armor Bag"                       -- from OpenableBeGone
ns.items[207077] = "Warmonger's Mail Armor Bag"                      -- from OpenableBeGone
ns.items[207076] = "Warmonger's Plate Armor Bag"                     -- from OpenableBeGone
ns.items[207075] = "Jingoist's Plate Armor Bag"                      -- from OpenableBeGone
ns.items[207074] = "Warmonger's Cloth Gear Bag"                      -- from OpenableBeGone
ns.items[207073] = "Warmonger's Cloth Equipment Bag"                 -- from OpenableBeGone
ns.items[207072] = "Jingoist's Cloth Equipment Bag"                  -- from OpenableBeGone
ns.items[207071] = "Jingoist's Cloth Gear Bag"                       -- from OpenableBeGone
ns.items[207070] = "Warmonger's Leather Gear Bag"                    -- from OpenableBeGone
ns.items[207069] = "Warmonger's Leather Equipment Bag"               -- from OpenableBeGone
ns.items[207068] = "Jingoist's Leather Equipment Bag"                -- from OpenableBeGone
ns.items[207067] = "Jingoist's Leather Gear Bag"                     -- from OpenableBeGone
ns.items[207066] = "Warmonger's Mail Equipment Bag"                  -- from OpenableBeGone
ns.items[207065] = "Warmonger's Mail Gear Bag"                       -- from OpenableBeGone
ns.items[207064] = "Jingoist's Mail Gear Bag"                        -- from OpenableBeGone
ns.items[207063] = "Jingoist's Mail Equipment Bag"                   -- from OpenableBeGone
ns.items[207053] = "Jingoist's Plate Gear Bag"                       -- from OpenableBeGone
ns.items[207052] = "Jingoist's Plate Equipment Bag"                  -- from OpenableBeGone
ns.items[207051] = "Warmonger's Plate Equipment Bag"                 -- from OpenableBeGone
ns.items[207050] = "Warmonger's Plate Gear Bag"                      -- from OpenableBeGone
ns.items[206271] = "Malicia's Hoard"                                 -- from OpenableBeGone
ns.items[206136] = "Heroic Dungeon Delver's Trophy Crest"            -- from OpenableBeGone
ns.items[206135] = "Heroic Dungeon Delver's Trophy Chest"
ns.items[206039] = "Enmity Bundle"                                   -- from OpenableBeGone
ns.items[206037] = "Ruby Flightstone"                                -- from OpenableBeGone
ns.items[206028] = "Chest of Gold"                                   -- from OpenableBeGone
ns.items[205983] = "Scentsational Niffen Treasures"
ns.items[205970] = "Azure Flightstone"                               -- from OpenableBeGone
ns.items[205968] = "Overflowing Loammian Supply Pack"                -- from OpenableBeGone
ns.items[205967] = "Cache of Aberrus Treasures"                      -- from OpenableBeGone
ns.items[205966] = "Cache of Aberrus Treasures"
ns.items[205965] = "Large Loammian Supply Pack"                      -- from OpenableBeGone
ns.items[205964] = "Small Loammian Supply Pack"
ns.items[205877] = "Adventurer's Footlocker"
ns.items[205374] = "Thankful Researcher's Scrounged Goods"           -- from OpenableBeGone
ns.items[205373] = "Researcher's Scrounged Goods"
ns.items[205372] = "Indebted Researcher's Scrounged Goods"           -- from OpenableBeGone
ns.items[205371] = "Appreciative Researcher's Scrounged Goods"
ns.items[205370] = "Researcher's Gift"
ns.items[205369] = "Appreciative Researcher's Gift"
ns.items[205368] = "Thankful Researcher's Gift"                      -- from OpenableBeGone
ns.items[205367] = "Indebted Researcher's Gift"
ns.items[205347] = "Gathered Niffen Resources"
ns.items[205346] = "Hidden Niffen Treasure"
ns.items[205288] = "Buried Niffen Collection"
ns.items[205248] = "Clanging Dirt-Covered Pouch"                     -- from OpenableBeGone
ns.items[205247] = "Clinking Dirt-Covered Pouch"
ns.items[205226] = "Cavern Racer's Purse"
ns.items[204911] = "Propagated Spore"                                -- from OpenableBeGone
ns.items[204726] = "Drake's Bountiful Chest"                         -- from OpenableBeGone
ns.items[204725] = "Drake's Hefty Chest"                             -- from OpenableBeGone
ns.items[204724] = "Drake's Small Chest"
ns.items[204723] = "Whelpling's Hefty Chest"                         -- from OpenableBeGone
ns.items[204722] = "Whelpling's Bountiful Chest"                     -- from OpenableBeGone
ns.items[204721] = "Whelpling's Small Chest"                         -- from OpenableBeGone
ns.items[204712] = "Brimming Loamm Niffen Supply Satchel"            -- from OpenableBeGone
ns.items[204636] = "Snarfang's Stomach Sac"                          -- from OpenableBeGone
ns.items[204403] = "Sack of Sack of Oddities"                        -- from OpenableBeGone
ns.items[204383] = "Sack of Oddities"                                -- from OpenableBeGone
ns.items[204381] = "Brimming Valdrakken Accord Supply Pack"
ns.items[204380] = "Brimming Maruuk Centaur Supply Satchel"          -- from OpenableBeGone
ns.items[204379] = "Brimming Iskaaran Supply Pack"                   -- from OpenableBeGone
ns.items[204378] = "Brimming Dragonscale Expedition Supply Pack"
ns.items[204359] = "Reach Raver's Purse"
ns.items[204346] = "Arclight Rumble Foil Box"                        -- from OpenableBeGone
ns.items[204307] = "Ornate Bronze Lockbox"                           -- from OpenableBeGone
ns.items[203959] = "Gurubashi Tribute"                               -- from OpenableBeGone
ns.items[203912] = "Penny Pouch o' Paragons"                         -- from OpenableBeGone
ns.items[203774] = "Big Bag o' Bijous"                               -- from OpenableBeGone
ns.items[203743] = "Jostled Gurubashi Cache"                         -- from OpenableBeGone
ns.items[203742] = "Waterlogged Gurubashi Cache"                     -- from OpenableBeGone
ns.items[203730] = "Rustic Winterpelt Supplies"                      -- from OpenableBeGone
ns.items[203724] = "Field Medic's Hazard Payout"                     -- from OpenableBeGone
ns.items[203700] = "Tattered Gift Package"                           -- from OpenableBeGone
ns.items[203699] = "Tattered Gift Package"                           -- from OpenableBeGone
ns.items[203681] = "Stormed Primalist Cache"
ns.items[203476] = "Primalist Cache"
ns.items[203450] = "Bottomless Bag of Skins"
ns.items[203449] = "Bottomless Bag of Herbs"
ns.items[203448] = "Bottomless Bag of Ore"
ns.items[203447] = "Bottomless Bag of Optional Goods"
ns.items[203444] = "Bottomless Bag of General Goods"
ns.items[203441] = "Bottomless Bag of Tailoring Goods"
ns.items[203440] = "Bottomless Bag of Leatherworking Goods"
ns.items[203439] = "Bottomless Bag of Jewelcrafting Goods"
ns.items[203438] = "Bottomless Bag of Inscription Goods"
ns.items[203437] = "Bottomless Bag of Engineering Goods"
ns.items[203436] = "Bottomless Bag of Enchanting Goods"
ns.items[203435] = "Bottomless Bag of Alchemy Goods"
ns.items[203434] = "Bottomless Bag of Blacksmithing Goods"
ns.items[203224] = "Valdrakken Surplus Chest"                        -- from OpenableBeGone
ns.items[203223] = "Valdrakken Supply Coffer"                        -- from OpenableBeGone
ns.items[203222] = "Maruuk Surplus Bundle"                           -- from OpenableBeGone
ns.items[203221] = "Maruuk Supply Sack"                              -- from OpenableBeGone
ns.items[203220] = "Iskaara Surplus Bag"                             -- from OpenableBeGone
ns.items[203218] = "Iskaara Supply Pouch"                            -- from OpenableBeGone
ns.items[203217] = "Dragonscale Surplus Crate"                       -- from OpenableBeGone
ns.items[203210] = "Dragonscale Supply Box"                          -- from OpenableBeGone
ns.items[202371] = "Glowing Primalist Cache"
ns.items[202183] = "Small Rumble Purse"                              -- from OpenableBeGone
ns.items[202172] = "Overflowing Satchel of Coins"
ns.items[202171] = "Dragon Purse"
ns.items[202142] = "Dragonbane Keep Strongbox"
ns.items[202122] = "Primal Chaos Cluster"
ns.items[202104] = "Weighted Sac of Swog Treasures"
ns.items[202103] = "Immaculate Sac of Swog Treasures"
ns.items[202102] = "Immaculate Sac of Swog Treasures"
ns.items[202101] = "Topped Trunk of Disenchanted Detritus"
ns.items[202100] = "Populous Pack of Castoff Cloth"
ns.items[202099] = "Stocked Sack of Hale Herbs"
ns.items[202098] = "Crowded Crate of Mined Materials"
ns.items[202097] = "Bulging Box of Skins and Scales"
ns.items[202083] = "Tyler's Test Box"
ns.items[202080] = "Cache of Vault Treasures"
ns.items[202079] = "Cache of Vault Treasures"
ns.items[202059] = "Jeweled Dragon's Heart"                          -- from Open-Sesame/OpenableBeGone
ns.items[202058] = "Timewatcher's Patience"
ns.items[202057] = "Earthwarden's Prize"
ns.items[202056] = "Keeper's Glory"
ns.items[202055] = "Dreamer's Vision"
ns.items[202054] = "Queen's Gift"
ns.items[202053] = "Jeweled Dragon's Heart"                          -- from Open-Sesame/OpenableBeGone
ns.items[202052] = "Timewatcher's Patience"
ns.items[202051] = "Earthwarden's Prize"
ns.items[202050] = "Keeper's Glory"
ns.items[202049] = "Dreamer's Vision"
ns.items[202048] = "Queen's Gift"
ns.items[201818] = "Twilight Strongbox"
ns.items[201817] = "Twilight Cache"
ns.items[201757] = "Plundered Supplies"
ns.items[201756] = "Bulging Coin Purse"
ns.items[201755] = "Obsidian Forgemaster's Strongbox"
ns.items[201754] = "Obsidian Forgemaster's Cache"
ns.items[201728] = "Vakril's Strongbox"
ns.items[201462] = "Curiously-Shaped Stomach"
ns.items[201439] = "Renewed Dream"
ns.items[201354] = "Bag of Plate Armor Reagents"
ns.items[201353] = "Bag of Mail Armor Reagents"
ns.items[201352] = "Bag of Leather Reagents"
ns.items[201343] = "Bag of Cloth Armor Reagents"
ns.items[201326] = "Draconic Satchel of Cooperation"
ns.items[201299] = "Docile Frosty Soul"
ns.items[201298] = "Docile Fiery Soul"
ns.items[201297] = "Docile Earthen Soul"
ns.items[201296] = "Docile Airy Soul"
ns.items[201252] = "10.0 Bronze PvP Chest"
ns.items[201251] = "Pillaged Contender's Strongbox"
ns.items[201250] = "Victorious Contender's Strongbox"
ns.items[200936] = "Encaged Earthen Soul"
ns.items[200934] = "Encaged Frosty Soul"
ns.items[200932] = "Encaged Airy Soul"
ns.items[200931] = "Encaged Fiery Soul"
ns.items[200611] = "Dragon Racing Purse - Third Place"
ns.items[200610] = "Dragon Racing Purse - Second Place"
ns.items[200609] = "Dragon Racing Purse - First Place"
ns.items[200516] = "Grand Hunt Spoils"
ns.items[200515] = "Grand Hunt Spoils"
ns.items[200513] = "Grand Hunt Spoils"
ns.items[200477] = "Stack of VIP Passes"
ns.items[200468] = "Grand Hunt Spoils"
ns.items[200300] = "Sack of Looted Treasures"
ns.items[200156] = "Amethyzarite Geode"
ns.items[200095] = "Supply-Laden Soup Pot"
ns.items[200094] = "Caravan Strongbox"
ns.items[200073] = "Valdrakken Treasures"
ns.items[200072] = "Dragonbane Keep Strongbox"
ns.items[200070] = "Obsidian Strongbox"
ns.items[200069] = "Obsidian Cache"
ns.items[199475] = "Overflowing Valdrakken Accord Supply Pack"
ns.items[199474] = "Overflowing Maruuk Centaur Supply Satchel"
ns.items[199473] = "Overflowing Iskaaran Supply Pack"
ns.items[199472] = "Overflowing Dragon Expedition Supply Pack"
ns.items[199342] = "Weighted Sac of Swog Treasures"
ns.items[199341] = "Regurgitated Sac of Swog Treasures"
ns.items[199192] = "Dragon Racer's Purse"
ns.items[199108] = "Bag of Discount Goods"
ns.items[198869] = "Large Valdrakken Accord Supply Pack"
ns.items[198868] = "Small Valdrakken Accord Supply Pack"
ns.items[198867] = "Large Iskaaran Supply Pack"
ns.items[198866] = "Small Iskaaran Supply Pack"
ns.items[198865] = "Large Dragon Expedition Supply Pack"
ns.items[198864] = "Large Maruuk Centaur Supply Satchel"
ns.items[198863] = "Small Dragon Expedition Supply Pack"
ns.items[198439] = "Aged Recipe in a Bottle"
ns.items[198438] = "Draconic Recipe in a Bottle"
ns.items[198172] = "Bundle of Fireworks"
ns.items[198171] = "Suspiciously Silent Crate Gold"
ns.items[198170] = "Suspiciously Silent Crate Silver"
ns.items[198169] = "Suspiciously Silent Crate Bronze"
ns.items[198168] = "Suspiciously Ticking Crate Gold"
ns.items[198167] = "Suspiciously Ticking Crate Silver"
ns.items[198166] = "Suspiciously Ticking Crate Bronze"
ns.items[194750] = "Professional Equipment"
ns.items[194419] = "Life Pool Herb Pouch"
ns.items[194072] = "Sack of Gold"
ns.items[193376] = "Adenedal's Tidy Purse"
ns.items[192892] = "Timewatcher's Patience"
ns.items[192891] = "Earthwarden's Prize Bronze"
ns.items[192890] = "Keeper's Glory Bronze"
ns.items[192889] = "Dreamer's Vision Bronze"
ns.items[192888] = "Queen's Gift Bronze"
ns.items[189765] = "Maruuk Centaur Supply Satchel"

