local _, ns = ...
ns.exclude = ns.exclude or {}

-- [ EXCLUSION DATABASE - 2026 CONSOLIDATED ]
-- Sorted by itemID (descending).
ns.exclude[280458] = { "Delver's Corroded Pouch of Undercoin",  "Item not Cache" }              -- 2026-08-19 Purchased
ns.exclude[268297] = { "Rattling Bag o'Gold",                   "Doesn't AutoOpen" }            -- 2026-08-09 Looted
ns.exclude[264475] = { "Umbral Tin Lockbox",                    "Locked" }                      -- in AutoOpenContainers
ns.exclude[262432] = { "Weathered Lockbox",                     "Locked" }                      -- from AutoOpenContainers
ns.exclude[226258] = { "Delver's Pouch of Reagents",            "Doesn't AutoOpen" }            --
ns.exclude[225249] = { "Rattling Bag o'Gold",                   "Doesn't AutoOpen" }            --
ns.exclude[221375] = { "Pack of Runed Harbinger Crests",        "Doesn't AutoOpen" }            --
ns.exclude[221373] = { "Satchel of Carved Harbinger Crests",    "Doesn't AutoOpen" }            --
ns.exclude[221268] = { "Pouch of Weathered Harbinger Crests",   "Doesn't AutoOpen" }            --
ns.exclude[220776] = { "Gilded Harbinger Crests",               "Doesn't AutoOpen" }            --
ns.exclude[220773] = { "Runed Harbinger Crests",                "Doesn't AutoOpen" }            --
ns.exclude[220767] = { "Carved Harbinger Crests",               "Doesn't AutoOpen" }            --
ns.exclude[220376] = { "Bismuth Lockbox",                       "LOCKED" }                      --  in AutoOpenContainers
ns.exclude[205423] = { "Shadowflame Residue Sack",              "Doesn't AutoOpen" }            --
ns.exclude[204712] = { "Brimming Loamm Niffen Satchel",         "Barter Logic (Manual)" }       --
ns.exclude[204307] = { "Ornate Bronze Lockbox",                 "LOCKED" }                      --  in AutoOpenContainers
ns.exclude[203743] = { "Jostled Gurubashi Cache",               "LOCKED" }                      --  in AutoOpenContainers
ns.exclude[202083] = { "Tyler's Test Box",                      "Test Items" }                  --
ns.exclude[202059] = { "Jeweled Dragon's Heart",                "Crafting Reagent" }            -- 
ns.exclude[202053] = { "Jeweled Dragon's Heart",                "Crafting Reagent" }            --
ns.exclude[201252] = { "10.0 Bronze PvP Chest",                 "Test Items" }                  -- 
ns.exclude[198657] = { "Forgotten Jewelry Box",                 "Requires Key (Locked)" }       -- 
ns.exclude[198395] = { "Dull Spined Clam",                      "Doesn't AutoOpen" }            -- 
ns.exclude[194037] = { "Heavy Chest",                           "Requires Key (Locked)" }       -- 
ns.exclude[192893] = { "Jeweled Dragon's Heart",                "Crafting Reagent" }            -- 
ns.exclude[191296] = { "Enchanted Lockbox",                     "Locked - Rogue" }              -- 
ns.exclude[191060] = { "Black Sack of Gems",                    "Doesn't AutoOpen" }            -- 
ns.exclude[190954] = { "Serevite Lockbox",                      "Send to Rogue/Sell" }          -- 
ns.exclude[190339] = { "Enlightened Offering",                  "Doesn't AutoOpen" }            -- 
ns.exclude[189452] = { "9.2 Mount Crafting Bag of Goodies",     "Test Item" }                   -- AutoOpenContainers
ns.exclude[189428] = { "9.2 Pet Battle Playtest Bag",           "Test Items" }                  -- 
ns.exclude[188796] = { "Cypher Test Item",                      "Test Items" }                  -- 
ns.exclude[188787] = { "Locked Broker Luggage",                 "Requires Key" }                -- 
ns.exclude[187502] = { "Byron Test Relic Box (Immediate)",      "Test Items" }                  -- 
ns.exclude[187494] = { "Byron Test Relic Box",                  "Test Items" }                  -- 
ns.exclude[187351] = { "Stygic Cluster",                        "Manual Use (BoA Bundle)" }     -- 
ns.exclude[186161] = { "Stygian Lockbox",                       "Requires Key" }                -- 
ns.exclude[186160] = { "Locked Artifact Case",                  "Requires Key (Locked)" }       -- 
ns.exclude[185940] = { "Pristine Survival Kit",                 "Level 60 Boost Lock" }         -- 
ns.exclude[184866] = { "Grummlepouch",                          "Doesn't AutoOpen" }            -- 
ns.exclude[184584] = { "Byron Test Callings Box",               "Test Items" }                  -- 
ns.exclude[180592] = { "Trapped Stonefiend",                    "Doesn't AutoOpen" }            -- 
ns.exclude[180533] = { "Solenium Lockbox",                      "Requires Key (Locked)" }       -- 
ns.exclude[180532] = { "Oxxein Lockbox",                        "Requires Key (Locked)" }       -- 
ns.exclude[180522] = { "Phaedrum Lockbox",                      "Requires Key (Locked)" }       -- 
ns.exclude[180380] = { "Lace Draperies",                        "Requires Tailoring 100" }      -- 
ns.exclude[180379] = { "Exquisitely Woven Rug",                 "Requires Tailoring  75" }      -- 
ns.exclude[179311] = { "Oxxein Lockbox",                        "Requires Key (Locked)" }       -- 
ns.exclude[178969] = { "Test Container",                        "Test Items" }                  -- 
ns.exclude[170502] = { "Waterlogged Toolbox",                   "User Preference (False)" }     -- 
ns.exclude[169475] = { "Barnacled Lockbox",                     "Locked Requires Key" }         -- 
ns.exclude[168124] = { "Cache of War Resources",                "Currency Transfer" }           -- 
ns.exclude[160268] = { "Bag of Armor (DNT)",                    "Test Items" }                  -- 
ns.exclude[157825] = { "Faronis Lockbox",                       "Doesn't AutoOpen" }            -- 
ns.exclude[157822] = { "Dreamweaver Lockbox",                   "Doesn't AutoOpen" }            -- 
ns.exclude[152922] = { "Brittle Krokul Chest",                  "Doesn't AutoOpen" }            -- 
ns.exclude[152108] = { "Legionfall Chest",                      "Doesn't AutoOpen" }            -- 
ns.exclude[152106] = { "Valarjar Strongbox",                    "Doesn't AutoOpen" }            -- 
ns.exclude[152103] = { "Dreamweaver Cache",                     "Doesn't AutoOpen" }            -- 
ns.exclude[143753] = { "Damp Pet Supplies",                     "Doesn't AutoOpen" }            -- 
ns.exclude[136926] = { "Nightmare Pod",                         "Doesn't AutoOpen" }            -- 
ns.exclude[121331] = { "Leystone Lockbox",                      "Locked Requires Key" }         -- 
ns.exclude[119000] = { "Highmaul Lockbox",                      "Locked Requires Key" }         -- 
ns.exclude[118697] = { "Big Bag of Pet Supplies",               "Doesn't AutoOpen" }            -- 
ns.exclude[118193] = { "Mysterious Shining Lockbox",            "Locked Requires Key" }         -- 
ns.exclude[116920] = { "True Steel Lockbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[106895] = { "Iron-Bound Junkbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 88567] = { "Ghost Iron Lockbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 88165] = { "Vine-Cracked Junkbox",                  "Send to Rogue/Sell" }          -- 
ns.exclude[ 68729] = { "Elementium Lockbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 63349] = { "Flame-Scarred Junkbox",                 "Send to Rogue/Sell" }          -- 
ns.exclude[ 46110] = { "Alchemist's Cache",                     "Locked Alchemist Only" }       -- 
ns.exclude[ 45986] = { "Tiny Titanium Lockbox",                 "Locked Requires Key" }         -- 
ns.exclude[ 45072] = { "Brightly Colored Egg",                  "Doesn't AutoOpen Anymore" }    -- 
ns.exclude[ 44700] = { "Brooding Darkwater Clam",               "Doesn't AutoOpen" }            -- 
ns.exclude[ 43624] = { "Titanium Lockbox",                      "Send to Rogue/Sell" }          -- 
ns.exclude[ 43622] = { "Froststeel Lockbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 43575] = { "Reinforced Junkbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 36781] = { "Darkwater Clam",                        "Doesn't AutoOpen" }            -- 
ns.exclude[ 34846] = { "Black Sack of Gems",                    "Doesn't AutoOpen?" }           -- 
ns.exclude[ 31952] = { "Khorium Lockbox",                       "Send to Rogue/Sell" }          -- 
ns.exclude[ 29569] = { "Strong Junkbox",                        "Send to Rogue/Sell" }          -- 
ns.exclude[ 27513] = { "Curious Crate",                         "Doesn't AutoOpen" }            -- 
ns.exclude[ 27481] = { "Heavy Supply Crate",                    "Doesn't AutoOpen" }            -- 
ns.exclude[ 24476] = { "Jaggal Clam",                           "Doesn't AutoOpen" }            -- 
ns.exclude[ 21743] = { "Large Cluster Rocket Recipes",          "Profession Locked" }           -- 
ns.exclude[ 21742] = { "Large Rocket Recipes",                  "Profession Locked" }           -- 
ns.exclude[ 21741] = { "Cluster Rocket Recipes",                "Profession Locked" }           -- 
ns.exclude[ 21740] = { "Small Rocket Recipes",                  "Profession Locked" }           -- 
ns.exclude[ 19425] = { "Mysterious Lockbox",                    "Send to Rogue/Sell" }          -- 
ns.exclude[ 16885] = { "Heavy Junkbox",                         "Send to Rogue/Sell" }          -- 
ns.exclude[ 16884] = { "Sturdy Junkbox",                        "Send to Rogue/Sell" }          -- 
ns.exclude[ 16883] = { "Worn Junkbox",                          "Send to Rogue/Sell" }          -- 
ns.exclude[ 16882] = { "Battered Junkbox",                      "Send to Rogue/Sell" }          -- 
ns.exclude[ 15874] = { "Soft-shelled Clam",                     "Doesn't AutoOpen" }            -- 
ns.exclude[ 13918] = { "Reinforced Locked Chest",               "Send to Rogue/Sell" }          -- 
ns.exclude[ 13875] = { "Ironbound Locked Chest",                "Send to Rogue/Sell" }          -- 
ns.exclude[ 12033] = { "Thaurissan Family Jewels",              "Send to Rogue/Sell" }          -- 
ns.exclude[  7973] = { "Big-Mouth Clams",                       "Doesn't AutoOpen" }            -- 
ns.exclude[  7870] = { "Thaumaturgy Vessel Lockbox",            "Send to Rogue/Sell" }          -- 
ns.exclude[  7209] = { "Tazan's Satchel",                       "Send to Rogue/Sell" }          -- 
ns.exclude[  6355] = { "Sturdy Locked Chest",                   "Send to Rogue/Sell" }          -- 
ns.exclude[  6354] = { "Small Locked Chest",                    "Send to Rogue/Sell" }          -- 
ns.exclude[  5760] = { "Eternium Lockbox",                      "Send to Rogue/Sell" }          -- 
ns.exclude[  5759] = { "Thorium Lockbox",                       "Send to Rogue/Sell" }          -- 
ns.exclude[  5758] = { "Mithril Lockbox",                       "Send to Rogue/Sell" }          -- 
ns.exclude[  5524] = { "Thick-shelled Clam",                    "Doesn't AutoOpen" }            -- 
ns.exclude[  5523] = { "Small Barnacled Clam",                  "Doesn't AutoOpen" }            -- 
ns.exclude[  4638] = { "Reinforced Steel Lockbox",              "Send to Rogue/Sell" }          -- 
ns.exclude[  4637] = { "Steel Lockbox",                         "Send to Rogue/Sell" }          -- 
ns.exclude[  4636] = { "Strong Iron Lockbox",                   "Send to Rogue/Sell" }          -- 
ns.exclude[  4634] = { "Iron Lockbox",                          "Send to Rogue/Sell" }          -- 
ns.exclude[  4633] = { "Heavy Bronze Lockbox",                  "Send to Rogue/Sell" }          -- 
ns.exclude[  4632] = { "Ornate Bronze Lockbox",                 "Send to Rogue/Sell" }          -- 


-- [ REVIEW: Locked/disabled signals | 2026-02-18 10:32:52 ]
ns.exclude[263869] = { "Primalist Necklace",                    "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263868] = { "Primalist Ring",                        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263867] = { "Primalist Cloak",                       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263866] = { "Primalist Leather Gloves",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263865] = { "Primalist Mail Gloves",                 "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263864] = { "Primalist Plate Gloves",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263863] = { "Primalist Cloth Gloves",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263862] = { "Primalist Cloth Boots",                 "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263861] = { "Primalist Plate Boots",                 "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263859] = { "Primalist Mail Boots",                  "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263822] = { "Primalist Leather Boots",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263776] = { "Primalist Leather Belt",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263740] = { "Primalist Mail Belt",                   "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263733] = { "Primalist Cloth Belt",                  "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263732] = { "Primalist Plate Belt",                  "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263731] = { "Primalist Plate Bracers",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263730] = { "Primalist Cloth Bracers",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263729] = { "Primalist Mail Bracers",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263728] = { "Primalist Leather Bracers",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263727] = { "Primalist Leather Spaulders",           "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263726] = { "Primalist Mail Spaulders",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263725] = { "Primalist Cloth Spaulders",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263724] = { "Primalist Plate Spaulders",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263722] = { "Primalist Plate Leggings",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263721] = { "Primalist Cloth Leggings",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263720] = { "Primalist Mail Leggings",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263719] = { "Primalist Leather Leggings",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263718] = { "Primalist Leather Chestpiece",          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263717] = { "Primalist Mail Chestpiece",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263716] = { "Primalist Cloth Chestpiece",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263715] = { "Primalist Plate Chestpiece",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263714] = { "Primalist Trinket",                     "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263713] = { "Primalist Leather Helm",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263712] = { "Primalist Mail Helm",                   "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263711] = { "Primalist Cloth Helm",                  "Gear Token" }                  -- AutoOpenContainers
ns.exclude[263710] = { "Primalist Plate Helm",                  "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174638] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174637] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174636] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174635] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174634] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174633] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174632] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174631] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[174630] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173425] = { "Black Empire Mail Bracers",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173424] = { "Black Empire Leather Bracers",          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173423] = { "Black Empire Cloth Bracers",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173422] = { "Black Empire Plate Bracers",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173420] = { "Black Empire Cloth Belt",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173419] = { "Black Empire Cloth Spaulders",          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173418] = { "Black Empire Cloth Leggings",           "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173417] = { "Black Empire Cloth Helm",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173416] = { "Black Empire Cloth Gloves",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173415] = { "Black Empire Cloth Boots",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173414] = { "Black Empire Cloth Robes",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173413] = { "Black Empire Leather Belt",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173412] = { "Black Empire Leather Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173411] = { "Black Empire Leather Leggings",         "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173410] = { "Black Empire Leather Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173409] = { "Black Empire Leather Gloves",           "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173408] = { "Black Empire Leather Boots",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173407] = { "Black Empire Leather Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173406] = { "Black Empire Mail Belt",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173405] = { "Black Empire Mail Spaulders",           "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173404] = { "Black Empire Mail Leggings",            "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173403] = { "Black Empire Mail Helm",                "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173402] = { "Black Empire Mail Gloves",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173401] = { "Black Empire Mail Boots",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173400] = { "Black Empire Mail Chestpiece",          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173399] = { "Black Empire Plate Belt",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173398] = { "Black Empire Plate Spaulders",          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173397] = { "Black Empire Plate Leggings",           "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173396] = { "Black Empire Plate Helm",               "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173395] = { "Black Empire Plate Gloves",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173394] = { "Black Empire Plate Boots",              "Gear Token" }                  -- AutoOpenContainers
ns.exclude[173393] = { "Black Empire Plate Chestpiece",         "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169485] = { "Benthic Gauntlets",                     "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169484] = { "Benthic Spaulders",                     "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169483] = { "Benthic Treads",                        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169482] = { "Benthic Leggings",                      "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169481] = { "Benthic Cloak",                         "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169480] = { "Benthic Chestguard",                    "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169479] = { "Benthic Helm",                          "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169478] = { "Benthic Bracers",                       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169477] = { "Benthic Girdle",                        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169343] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169342] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169341] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169340] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169339] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169338] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169337] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169336] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[169335] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166537] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166536] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166535] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166534] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166533] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166532] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166531] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166530] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166529] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166515] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166514] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166513] = { "Relinquished Azerite Chestpiece",       "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166512] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166511] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166510] = { "Relinquished Azerite Helm",             "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166509] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166508] = { "Relinquished Azerite Spaulders",        "Gear Token" }                  -- AutoOpenContainers
ns.exclude[166505] = { "Relinquished Azerite Spaulders",        "Gear Token" } -- AutoOpenContainers

