local _, ns = ...
ns.exclude = ns.exclude or {}

-- [ EXCLUSION DATABASE - 2026 CONSOLIDATED ]
-- Sorted by itemID (descending).

ns.exclude[264475] = { "Umbral Tin Lockbox", "LOCKED" }                                     --  in AutoOpenContainers
ns.exclude[262432] = { "Weathered Lockbox", "Locked - Rogue/Key" }                          -- from AutoOpenContainers
ns.exclude[226258] = { "Delver's Pouch of Reagents", "Does not open" }
ns.exclude[225249] = { "Rattling Bag o'Gold", "Not a container" }
ns.exclude[221375] = { "Pack of Runed Harbinger Crests", "Currency (Manual use)" }
ns.exclude[221373] = { "Satchel of Carved Harbinger Crests", "Currency (Manual use)" }
ns.exclude[221268] = { "Pouch of Weathered Harbinger Crests", "Currency (Manual use)" }
ns.exclude[220776] = { "Gilded Harbinger Crests", "Currency (Manual use)" }
ns.exclude[220773] = { "Runed Harbinger Crests", "Currency (Manual use)" }
ns.exclude[220767] = { "Carved Harbinger Crests", "Currency (Manual use)" }
ns.exclude[220376] = { "Bismuth Lockbox", "LOCKED" }    --  in AutoOpenContainers
ns.exclude[205423] = { "Shadowflame Residue Sack", "Manual use only" }
ns.exclude[204712] = { "Brimming Loamm Niffen Satchel", "Barter Logic (Manual)" }
ns.exclude[204307] = { "Ornate Bronze Lockbox", "LOCKED" }  --  in AutoOpenContainers
ns.exclude[203743] = { "Jostled Gurubashi Cache", "LOCKED" } --  in AutoOpenContainers
ns.exclude[202083] = { "Tyler's Test Box", "Test Items" }
ns.exclude[202059] = { "Jeweled Dragon's Heart", "Crafting Reagent" }
ns.exclude[202053] = { "Jeweled Dragon's Heart", "Crafting Reagent" }
ns.exclude[201252] = { "10.0 Bronze PvP Chest", "Test Items" }
ns.exclude[198657] = { "Forgotten Jewelry Box", "Requires Key (Locked)" }
ns.exclude[198395] = { "Dull Spined Clam", "Clams Cannot AutoOpen" }
ns.exclude[194037] = { "Heavy Chest", "Requires Key (Locked)" }
ns.exclude[192893] = { "Jeweled Dragon's Heart", "Crafting Reagent" }
ns.exclude[191296] = { "Enchanted Lockbox", "Locked - Rogue/Key" }
ns.exclude[191060] = { "Black Sack of Gems", "Drops from Raid Boss" }
ns.exclude[190954] = { "Serevite Lockbox", "Locked - Rogue/Key" }
ns.exclude[190339] = { "Enlightened Offering", "Rep Token / Manual Use" }
ns.exclude[189452] = { "9.2 Mount Crafting Bag of Goodies", "Test Item" } -- AutoOpenContainers
ns.exclude[189428] = { "9.2 Pet Battle Playtest Bag", "Test Items" }
ns.exclude[188796] = { "Cypher Test Item", "Test Items" }
ns.exclude[188787] = { "Locked Broker Luggage", "Requires Key" }
ns.exclude[187502] = { "Byron Test Relic Box (Immediate)", "Test Items" }
ns.exclude[187494] = { "Byron Test Relic Box", "Test Items" }
ns.exclude[187351] = { "Stygic Cluster", "Manual Use (BoA Bundle)" }
ns.exclude[186161] = { "Stygian Lockbox", "Requires Key" }
ns.exclude[186160] = { "Locked Artifact Case", "Requires Key (Locked)" }
ns.exclude[185940] = { "Pristine Survival Kit", "Level 60 Boost Lock" }
ns.exclude[184866] = { "Grummlepouch", "Item (Not a bag)" }
ns.exclude[184584] = { "Byron Test Callings Box", "Test Items" }
ns.exclude[180592] = { "Trapped Stonefiend", "Pet (Not a bag)" }
ns.exclude[180533] = { "Solenium Lockbox", "Requires Key (Locked)" }
ns.exclude[180532] = { "Oxxein Lockbox", "Requires Key (Locked)" }
ns.exclude[180522] = { "Phaedrum Lockbox", "Requires Key (Locked)" }
ns.exclude[180380] = { "Lace Draperies", "Requires Tailoring 100 (Crafting)" }
ns.exclude[180379] = { "Exquisitely Woven Rug", "Requires Tailoring 75 (Crafting)" }
ns.exclude[179311] = { "Oxxein Lockbox", "Requires Key (Locked)" }
ns.exclude[178969] = { "Test Container", "Test Items" }
ns.exclude[170502] = { "Waterlogged Toolbox", "User Preference (False)" }
ns.exclude[169475] = { "Barnacled Lockbox", "Locked - Requires Key" }
ns.exclude[168124] = { "Cache of War Resources", "Currency Transfer (Manual)" }
ns.exclude[160268] = { "Bag of Armor (DNT)", "Test Items" }
ns.exclude[157825] = { "Faronis Lockbox", "Does Not Auto Open" }
ns.exclude[157822] = { "Dreamweaver Lockbox", "Does Not Auto Open" }
ns.exclude[152922] = { "Brittle Krokul Chest", "Does Not Auto Open" }
ns.exclude[152108] = { "Legionfall Chest", "Does Not Auto Open" }
ns.exclude[152106] = { "Valarjar Strongbox", "Does Not Auto Open" }
ns.exclude[152103] = { "Dreamweaver Cache", "Does Not Auto Open" }
ns.exclude[143753] = { "Damp Pet Supplies", "Does Not Auto Open" }
ns.exclude[136926] = { "Nightmare Pod", "Does Not Auto Open" }
ns.exclude[121331] = { "Leystone Lockbox", "Locked - Requires Key" }
ns.exclude[119000] = { "Highmaul Lockbox", "Locked - Requires Key" }
ns.exclude[118697] = { "Big Bag of Pet Supplies", "Does Not Auto Open" }
ns.exclude[118193] = { "Mysterious Shining Lockbox", "Locked - Requires Key" }
ns.exclude[116920] = { "True Steel Lockbox", "Locked - Rogue/Key" }
ns.exclude[106895] = { "Iron-Bound Junkbox", "Locked (Rogue Pick)" }
ns.exclude[ 88567] = { "Ghost Iron Lockbox", "Locked - Requires Key" }
ns.exclude[ 88165] = { "Vine-Cracked Junkbox", "Locked - Requires Rogue Pick" }
ns.exclude[ 68729] = { "Elementium Lockbox", "Locked - Requires Key" }
ns.exclude[ 63349] = { "Flame-Scarred Junkbox", "Locked - Requires Rogue Pick" }
ns.exclude[ 46110] = { "Alchemist's Cache", "Profession Locked (Alchemist Only)" }
ns.exclude[ 45986] = { "Tiny Titanium Lockbox", "Locked - Requires Key" }
ns.exclude[ 44700] = { "Brooding Darkwater Clam", "Does Not Open" }
ns.exclude[ 43624] = { "Titanium Lockbox", "Locked - Requires Key" }
ns.exclude[ 43622] = { "Froststeel Lockbox", "Locked - Requires Key" }
ns.exclude[ 43575] = { "Reinforced Junkbox", "Locked - Requires Rogue" }
ns.exclude[ 36781] = { "Darkwater Clam", "Clams Cannot AutoOpen" }
ns.exclude[ 34846] = { "Black Sack of Gems", "Drops from Raid Boss" }
ns.exclude[ 31952] = { "Khorium Lockbox", "Requires Key (Locked)" }
ns.exclude[ 29569] = { "Strong Junkbox", "Requires Rogue Pick (Locked)" }
ns.exclude[ 27513] = { "Curious Crate", "Does Not Open" }
ns.exclude[ 27481] = { "Heavy Supply Crate", "Manual use / False positive" }
ns.exclude[ 24476] = { "Jaggal Clam", "Does Not Open" }
ns.exclude[ 21743] = { "Large Cluster Rocket Recipes", "Profession Locked (Manual)" }
ns.exclude[ 21742] = { "Large Rocket Recipes", "Profession Locked (Manual)" }
ns.exclude[ 21741] = { "Cluster Rocket Recipes", "Profession Locked (Manual)" }
ns.exclude[ 21740] = { "Small Rocket Recipes", "Profession Locked (Manual)" }
ns.exclude[ 19425] = { "Mysterious Lockbox", "Locked - Rogue/Key" }
ns.exclude[ 16885] = { "Heavy Junkbox", "Locked - Rogue/Key" }
ns.exclude[ 16884] = { "Sturdy Junkbox", "Locked - Rogue/Key" }
ns.exclude[ 16883] = { "Worn Junkbox", "Locked - Rogue/Key" }
ns.exclude[ 16882] = { "Battered Junkbox", "Locked - Rogue/Key" }
ns.exclude[ 15874] = { "Soft-shelled Clam", "Clams Cannot AutoOpen" }
ns.exclude[ 13918] = { "Reinforced Locked Chest", "Locked - Rogue/Key" }
ns.exclude[ 13875] = { "Ironbound Locked Chest", "Locked - Rogue/Key" }
ns.exclude[ 12033] = { "Thaurissan Family Jewels", "Locked - Rogue/Key" }
ns.exclude[  7973] = { "Big-Mouth Clams", "Clams Cannot AutoOpen" }
ns.exclude[  7870] = { "Thaumaturgy Vessel Lockbox", "Locked - Rogue/Key" }
ns.exclude[  7209] = { "Tazan's Satchel", "Locked - Rogue/Key" }
ns.exclude[  6355] = { "Sturdy Locked Chest", "Locked - Rogue/Key" }
ns.exclude[  6354] = { "Small Locked Chest", "Locked - Rogue/Key" }
ns.exclude[  5760] = { "Eternium Lockbox", "Locked - Rogue/Key" }
ns.exclude[  5759] = { "Thorium Lockbox", "Locked - Rogue/Key" }
ns.exclude[  5758] = { "Mithril Lockbox", "Locked - Rogue/Key" }
ns.exclude[  5524] = { "Thick-shelled Clam", "Clams Cannot AutoOpen" }
ns.exclude[  5523] = { "Small Barnacled Clam", "Clams Cannot AutoOpen" }
ns.exclude[  4638] = { "Reinforced Steel Lockbox", "Locked - Rogue/Key" }
ns.exclude[  4637] = { "Steel Lockbox", "Locked - Rogue/Key" }
ns.exclude[  4636] = { "Strong Iron Lockbox", "Locked - Rogue/Key" }
ns.exclude[  4634] = { "Iron Lockbox", "Locked - Rogue/Key" }
ns.exclude[  4633] = { "Heavy Bronze Lockbox", "Locked - Rogue/Key" }
ns.exclude[  4632] = { "Ornate Bronze Lockbox", "Locked - Rogue/Key" }


-- [ REVIEW: Locked/disabled signals | 2026-02-18 10:32:52 ]
ns.exclude[174638] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[174637] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[174636] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[174635] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[174634] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[174633] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[174632] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[174631] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[174630] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[173425] = { "Black Empire Mail Bracers", "Gear Token" } -- AutoOpenContainers
ns.exclude[173424] = { "Black Empire Leather Bracers", "Gear Token" } -- AutoOpenContainers
ns.exclude[173423] = { "Black Empire Cloth Bracers", "Gear Token" } -- AutoOpenContainers
ns.exclude[173422] = { "Black Empire Plate Bracers", "Gear Token" } -- AutoOpenContainers
ns.exclude[173420] = { "Black Empire Cloth Belt", "Gear Token" } -- AutoOpenContainers
ns.exclude[173419] = { "Black Empire Cloth Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[173418] = { "Black Empire Cloth Leggings", "Gear Token" } -- AutoOpenContainers
ns.exclude[173417] = { "Black Empire Cloth Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[173416] = { "Black Empire Cloth Gloves", "Gear Token" } -- AutoOpenContainers
ns.exclude[173415] = { "Black Empire Cloth Boots", "Gear Token" } -- AutoOpenContainers
ns.exclude[173414] = { "Black Empire Cloth Robes", "Gear Token" } -- AutoOpenContainers
ns.exclude[173413] = { "Black Empire Leather Belt", "Gear Token" } -- AutoOpenContainers
ns.exclude[173412] = { "Black Empire Leather Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[173411] = { "Black Empire Leather Leggings", "Gear Token" } -- AutoOpenContainers
ns.exclude[173410] = { "Black Empire Leather Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[173409] = { "Black Empire Leather Gloves", "Gear Token" } -- AutoOpenContainers
ns.exclude[173408] = { "Black Empire Leather Boots", "Gear Token" } -- AutoOpenContainers
ns.exclude[173407] = { "Black Empire Leather Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[173406] = { "Black Empire Mail Belt", "Gear Token" } -- AutoOpenContainers
ns.exclude[173405] = { "Black Empire Mail Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[173404] = { "Black Empire Mail Leggings", "Gear Token" } -- AutoOpenContainers
ns.exclude[173403] = { "Black Empire Mail Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[173402] = { "Black Empire Mail Gloves", "Gear Token" } -- AutoOpenContainers
ns.exclude[173401] = { "Black Empire Mail Boots", "Gear Token" } -- AutoOpenContainers
ns.exclude[173400] = { "Black Empire Mail Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[173399] = { "Black Empire Plate Belt", "Gear Token" } -- AutoOpenContainers
ns.exclude[173398] = { "Black Empire Plate Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[173397] = { "Black Empire Plate Leggings", "Gear Token" } -- AutoOpenContainers
ns.exclude[173396] = { "Black Empire Plate Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[173395] = { "Black Empire Plate Gloves", "Gear Token" } -- AutoOpenContainers
ns.exclude[173394] = { "Black Empire Plate Boots", "Gear Token" } -- AutoOpenContainers
ns.exclude[173393] = { "Black Empire Plate Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[169485] = { "Benthic Gauntlets", "Gear Token" } -- AutoOpenContainers
ns.exclude[169484] = { "Benthic Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[169483] = { "Benthic Treads", "Gear Token" } -- AutoOpenContainers
ns.exclude[169482] = { "Benthic Leggings", "Gear Token" } -- AutoOpenContainers
ns.exclude[169481] = { "Benthic Cloak", "Gear Token" } -- AutoOpenContainers
ns.exclude[169480] = { "Benthic Chestguard", "Gear Token" } -- AutoOpenContainers
ns.exclude[169479] = { "Benthic Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[169478] = { "Benthic Bracers", "Gear Token" } -- AutoOpenContainers
ns.exclude[169477] = { "Benthic Girdle", "Gear Token" } -- AutoOpenContainers
ns.exclude[169343] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[169342] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[169341] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[169340] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[169339] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[169338] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[169337] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[169336] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[169335] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166537] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166536] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166535] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166534] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166533] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166532] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166531] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166530] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166529] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166515] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166514] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166513] = { "Relinquished Azerite Chestpiece", "Gear Token" } -- AutoOpenContainers
ns.exclude[166512] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166511] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166510] = { "Relinquished Azerite Helm", "Gear Token" } -- AutoOpenContainers
ns.exclude[166509] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166508] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers
ns.exclude[166505] = { "Relinquished Azerite Spaulders", "Gear Token" } -- AutoOpenContainers

