local _, ns = ...
ns.items = ns.items or {}

ns.items[269007] = "Preyseeker's Glittering Coin Pouch"              -- from AutoOpenContainers
ns.items[269006] = "Preyseeker's Gleaming Coin Pouch"                -- from AutoOpenContainers
ns.items[269005] = "Preyseeker's Glinting Coin Pouch"                -- from AutoOpenContainers
ns.items[268545] = "Aspiring Preyseeker's Chest"                     -- from AutoOpenContainers
ns.items[268490] = "Apex Cache"                                      -- from AutoOpenContainers
ns.items[268489] = "Surplus Bag of Party Favors"                     -- from AutoOpenContainers
ns.items[268488] = "Overflowing Abundant Satchel"                    -- from AutoOpenContainers
ns.items[268487] = "Avid Learner's Supply Pack"                      -- from AutoOpenContainers
ns.items[268485] = "Victorious Stormarion Pinnacle Cache"            -- from AutoOpenContainers
ns.items[267299] = "Slayer's Duellum Trove"                          -- from AutoOpenContainers
ns.items[265995] = "Quel'Thalas Adventurer's Cache"                  -- from AutoOpenContainers
ns.items[265780] = "Amani-Bound Coffer"                              -- Rare spawn chest in the Amani forest regions
ns.items[264988] = "Endgame Essentials"                              -- from AutoOpenContainers
ns.items[264972] = "Voidstorm Victuals"                              -- from AutoOpenContainers
ns.items[264587] = "Ani's Trinket Bag"                               -- from AutoOpenContainers
ns.items[264500] = "Reliquary Storage Crate"                         -- Exploration-themed container
ns.items[264470] = "Ash-Tied Offering"                               -- from AutoOpenContainers
ns.items[264274] = "Fabled Adventurer's Cache"                       -- from AutoOpenContainers
ns.items[263934] = "Chest of Gold"                                   -- from AutoOpenContainers
ns.items[263869] = "Primalist Necklace"                              -- from AutoOpenContainers
ns.items[263868] = "Primalist Ring"                                  -- from AutoOpenContainers
ns.items[263867] = "Primalist Cloak"                                 -- from AutoOpenContainers
ns.items[263866] = "Primalist Leather Gloves"                        -- from AutoOpenContainers
ns.items[263865] = "Primalist Mail Gloves"                           -- from AutoOpenContainers
ns.items[263864] = "Primalist Plate Gloves"                          -- from AutoOpenContainers
ns.items[263863] = "Primalist Cloth Gloves"                          -- from AutoOpenContainers
ns.items[263862] = "Primalist Cloth Boots"                           -- from AutoOpenContainers
ns.items[263861] = "Primalist Plate Boots"                           -- from AutoOpenContainers
ns.items[263859] = "Primalist Mail Boots"                            -- from AutoOpenContainers
ns.items[263822] = "Primalist Leather Boots"                         -- from AutoOpenContainers
ns.items[263776] = "Primalist Leather Belt"                          -- from AutoOpenContainers
ns.items[263740] = "Primalist Mail Belt"                             -- from AutoOpenContainers
ns.items[263733] = "Primalist Cloth Belt"                            -- from AutoOpenContainers
ns.items[263732] = "Primalist Plate Belt"                            -- from AutoOpenContainers
ns.items[263731] = "Primalist Plate Bracers"                         -- from AutoOpenContainers
ns.items[263730] = "Primalist Cloth Bracers"                         -- from AutoOpenContainers
ns.items[263729] = "Primalist Mail Bracers"                          -- from AutoOpenContainers
ns.items[263728] = "Primalist Leather Bracers"                       -- from AutoOpenContainers
ns.items[263727] = "Primalist Leather Spaulders"                     -- from AutoOpenContainers
ns.items[263726] = "Primalist Mail Spaulders"                        -- from AutoOpenContainers
ns.items[263725] = "Primalist Cloth Spaulders"                       -- from AutoOpenContainers
ns.items[263724] = "Primalist Plate Spaulders"                       -- from AutoOpenContainers
ns.items[263722] = "Primalist Plate Leggings"                        -- from AutoOpenContainers
ns.items[263721] = "Primalist Cloth Leggings"                        -- from AutoOpenContainers
ns.items[263720] = "Primalist Mail Leggings"                         -- from AutoOpenContainers
ns.items[263719] = "Primalist Leather Leggings"                      -- from AutoOpenContainers
ns.items[263718] = "Primalist Leather Chestpiece"                    -- from AutoOpenContainers
ns.items[263717] = "Primalist Mail Chestpiece"                       -- from AutoOpenContainers
ns.items[263716] = "Primalist Cloth Chestpiece"                      -- from AutoOpenContainers
ns.items[263715] = "Primalist Plate Chestpiece"                      -- from AutoOpenContainers
ns.items[263714] = "Primalist Trinket"                               -- from AutoOpenContainers
ns.items[263713] = "Primalist Leather Helm"                          -- from AutoOpenContainers
ns.items[263712] = "Primalist Mail Helm"                             -- from AutoOpenContainers
ns.items[263711] = "Primalist Cloth Helm"                            -- from AutoOpenContainers
ns.items[263710] = "Primalist Plate Helm"                            -- from AutoOpenContainers
ns.items[263468] = "Stormarion Spoils"                               -- from AutoOpenContainers
ns.items[263467] = "Avid Learner's Supply Pack"                      -- from AutoOpenContainers
ns.items[263466] = "Overflowing Abundant Satchel"                    -- from AutoOpenContainers
ns.items[263465] = "Surplus Bag of Party Favors"                     -- from AutoOpenContainers
ns.items[263433] = "Overflowing Silvermoon Trove"                    -- from AutoOpenContainers
ns.items[263400] = "Cache of Delver's Spoils"                        -- from AutoOpenContainers
ns.items[263179] = "Delver's Cosmetic Surprise Bag"                  -- from AutoOpenContainers
ns.items[263178] = "Delver's Starter Kit"                            -- from AutoOpenContainers
ns.items[263012] = "Thalassian Chest"                                -- Common world container found in Eversong Woods
ns.items[263010] = "Overflowing Abundant Satchel"                    -- Reward for high-threshold event completion.
ns.items[263000] = "Pinnacle Cache"                                  -- Weekly world event reward.
ns.items[262938] = "Preyseeker's Champion Sack"                      -- from AutoOpenContainers
ns.items[262936] = "Preyseeker's Veteran Sack"                       -- from AutoOpenContainers
ns.items[262928] = "Preyseeker's Adventurer Sack"                    -- from AutoOpenContainers
ns.items[262662] = "Thalassian Distinguishment"                      -- from AutoOpenContainers
ns.items[262635] = "Cache of Delver's Spoils"                        -- from AutoOpenContainers
ns.items[262634] = "Preyseeker's Cache of Voidlight Marl"            -- from AutoOpenContainers
ns.items[262633] = "Preyseeker's Cache of Champion Dawncrests"       -- from AutoOpenContainers
ns.items[262632] = "Preyseeker's Cache of Coffer Key Shards"         -- from AutoOpenContainers
ns.items[262631] = "Preyseeker's Cache of Anguish"                   -- from AutoOpenContainers
ns.items[262630] = "Preyseeker's Box of Voidlight Marl"              -- from AutoOpenContainers
ns.items[262629] = "Preyseeker's Box of Veteran Dawncrests"          -- from AutoOpenContainers
ns.items[262627] = "Preyseeker's Box of Coffer Key Shards"           -- from AutoOpenContainers
ns.items[262626] = "Preyseeker's Box of Anguish"                     -- from AutoOpenContainers
ns.items[262624] = "Preyseeker's Satchel of Anguish"                 -- from AutoOpenContainers
ns.items[262623] = "Preyseeker's Satchel of Adventurer Dawncrests"   -- from AutoOpenContainers
ns.items[262622] = "Preyseeker's Satchel of Coffer Key Shards"       -- from AutoOpenContainers
ns.items[262596] = "Preyseeker's Satchel of Voidlight Marl"          -- from AutoOpenContainers
ns.items[262349] = "Satchel of Compensation"                         -- from AutoOpenContainers
ns.items[262346] = "Preyseeker's Champion Chest"                     -- from AutoOpenContainers
ns.items[262184] = "Gemmed Elven Chest"                              -- Housing-specific world container
ns.items[262007] = "Miner's Void-Cracked Crate"                      -- Mining world treasure.
ns.items[262006] = "HerbalistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Root-Bound Satchel" -- Herbalism world treasure.
ns.items[262005] = "Ancient ArcanistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Scrollcase"  -- Inscription world treasure.
ns.items[262004] = "Sun-Bleached Tanning Rack"                       -- Leatherworking world treasure.
ns.items[262003] = "Void-Tainted Mortar"                             -- Alchemy world treasure.
ns.items[262002] = "Weathered ExplorerÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Kit"       -- Engineering world treasure.
ns.items[262001] = "Forgotten Jewel-Studded Case"                    -- Jewelcrafting world treasure.
ns.items[261500] = "Voidspire Fragment Crate"                        -- Raid/Dungeon-related reward
ns.items[261050] = "Void-Slicked Strongbox"                          -- High-end world loot from Ghostlands rares.
ns.items[261040] = "Lost Voidstorm Satchel"                          -- Rare world treasure containing mining materials
ns.items[261010] = "Valeera's Shadow-Stash"                          -- Companion reward bag
ns.items[260979] = "Victorious Stormarion Cache"                     -- from AutoOpenContainers
ns.items[260940] = "Victorious Stormarion Pinnacle Cache"            -- from AutoOpenContainers
ns.items[260545] = "Master Tailor's Surplus Reagents"                -- from AutoOpenContainers
ns.items[260544] = "Master Skinner's Surplus Reagents"               -- from AutoOpenContainers
ns.items[260543] = "Master Miner's Surplus Reagents"                 -- from AutoOpenContainers
ns.items[260542] = "Master Leatherworker's Surplus Reagents"         -- from AutoOpenContainers
ns.items[260541] = "Master Jewelcrafter's Surplus Reagents"          -- from AutoOpenContainers
ns.items[260540] = "Master Scribe's Surplus Reagents"                -- from AutoOpenContainers
ns.items[260539] = "Master Herbalist's Surplus Reagents"             -- from AutoOpenContainers
ns.items[260538] = "Master Engineer's Surplus Reagents"              -- from AutoOpenContainers
ns.items[260537] = "Master Enchanter's Surplus Reagents"             -- from AutoOpenContainers
ns.items[260536] = "Master Smith's Surplus Reagents"                 -- from AutoOpenContainers
ns.items[260534] = "Master Alchemist's Surplus Reagents"             -- from AutoOpenContainers
ns.items[260215] = "Ancient Haranir Urn"                             -- Ritual-themed container in the Harandar forest.
ns.items[260193] = "Fabled Veteran's Cache"                          -- from AutoOpenContainers
ns.items[260173] = "Crystallized Dawnlight Manaflux"                 -- from AutoOpenContainers
ns.items[260112] = "Honored Warrior's Cache"                         -- Treasure found in Zul'Aman
ns.items[260100] = "Sun-Blessed Trunk"                               -- Light-corrupted area treasure in Quel'Danas.
ns.items[260020] = "Reliquary Storage Crate"                         -- Exploration-themed container found in world outposts.
ns.items[260007] = "Miner's Void-Cracked Crate"
ns.items[260006] = "HerbalistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Root-Bound Satchel"
ns.items[260005] = "Ancient ArcanistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Scrollcase"
ns.items[260004] = "Sun-Bleached Tanning Rack"
ns.items[260003] = "Void-Tainted Mortar"
ns.items[260002] = "Weathered ExplorerÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Kit"
ns.items[260001] = "Forgotten Jewel-Studded Case"
ns.items[259510] = "Glowing Haranir Seed-Pod"                        -- Interactive zone container (Harandar)
ns.items[259505] = "Heavy Amani-Bound Coffer"                        -- Rare high-capacity forest chest
ns.items[259500] = "Large Thalassian Trunk"                          -- Rare high-capacity world chest
ns.items[259334] = "Overflowing Singularity Trove"                   -- from AutoOpenContainers
ns.items[259203] = "Bag of Cracked Orebits"
ns.items[259202] = "Pouch of Sprouted Clippings"
ns.items[259201] = "Pouch of Mystic Grindings"
ns.items[259200] = "Bag of Wild Skinnings"
ns.items[259150] = "Amani-Bound Coffer"                              -- Rare spawn forest chest in Amani territory.
ns.items[259130] = "Miner's Void-Cracked Crate"                      -- Mining world trea
ns.items[259125] = "HerbalistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Root-Bound Satchel" -- Herbalism world treasure
ns.items[259120] = "Ancient ArcanistÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Scrollcase"  -- Inscription one-time treasure
ns.items[259115] = "Sun-Bleached Tanning Rack"                       -- Leatherworking one-time treasure
ns.items[259110] = "Void-Tainted Mortar"                             -- Alchemy one-time treasure
ns.items[259105] = "Weathered ExplorerÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s Kit"       -- Engineering one-time treasure
ns.items[259101] = "Forgotten Jewel-Studded Case"                    -- Jewelcrafting one-time treasure
ns.items[259100] = "Harandar Seasonings Crate"                       -- Cooking-specific material container
ns.items[259086] = "Void-Touched Satchel of Cooperation"             -- from AutoOpenContainers
ns.items[259012] = "Sun-Blessed Pinnacle Cache"
ns.items[259011] = "Victorious Stormarion Pinnacle Cache"
ns.items[259010] = "Wriggling Pinnacle Cache"
ns.items[259005] = "Haranir Roots-Tender Box"                        -- Harandar zone container
ns.items[258990] = "Void-Slicked Strongbox"                          -- High-end Ghostlands loot
ns.items[258839] = "Concealed Catalogue"                             -- from AutoOpenContainers
ns.items[258810] = "Ancient Haranir Urn"                             -- Harandar zone ritual object
ns.items[258700] = "Sun-Blessed Trunk"                               -- Light-corrupted area container
ns.items[258620] = "Field Medic's Hazard Payout"                     -- from AutoOpenContainers
ns.items[258615] = "Reliquary Storage Crate"                         -- Exploration treasure
ns.items[258534] = "Illustrious Contender's Strongbox"               -- from AutoOpenContainers
ns.items[258520] = "Gemmed Elven Chest"                              -- Silvermoon-themed housing container
ns.items[258430] = "Shattered Sun Offensive Requisition"             -- Reintroduced faction-themed cache
ns.items[258420] = "Void-Purged Reliquary"                           -- Campaign quest reward
ns.items[258415] = "Zul'Aman Tribute Chest"                          -- Challenge-based reward container
ns.items[258410] = "Thalassian Emissary's Footlocker"                -- High-tier reputation reward
ns.items[258400] = "Amani-Bound Coffer"                              -- Amani forest rare chest
ns.items[258305] = "Thalassian Chest"                                -- Eversong Woods common container
ns.items[258279] = "[DNT] Big Pouch of Supplies"                     -- from AutoOpenContainers
ns.items[258210] = "Lost Voidstorm Satchel"                          -- Rare Voidstorm treasure
ns.items[258150] = "Honored Warrior's Cache"                         -- Zul'Aman treasure
ns.items[258120] = "Void-Touched Lockbox"                            -- High-level world container
ns.items[258075] = "Honored Warrior's Cache"                         -- Treasure chest found within Zul'Aman.
ns.items[258050] = "Amani War-Spoils"                                -- Zul'Aman themed chest
ns.items[258001] = "Sunwell-Infused Satchel"                         -- General world loot container
ns.items[257603] = "Primalist Weapon"                                -- from AutoOpenContainers
ns.items[257026] = "Preyseeker's Veteran Chest"                      -- from AutoOpenContainers
ns.items[257023] = "Preyseeker's Adventurer Chest"                   -- from AutoOpenContainers
ns.items[256055] = "Overflowing Hara'ti Trove"                       -- from AutoOpenContainers
ns.items[255704] = "Huge Bag of Midnight Inscription Goods"          -- from AutoOpenContainers
ns.items[255703] = "Huge Bag of Midnight Blacksmithing Goods"        -- from AutoOpenContainers
ns.items[255691] = "Huge Bag of Midnight Tailoring Goods"            -- from AutoOpenContainers
ns.items[255690] = "Huge Bag of Midnight Enchanting Goods"           -- from AutoOpenContainers
ns.items[255689] = "Huge Bag of Midnight Engineering Goods"          -- from AutoOpenContainers
ns.items[255687] = "Huge Bag of Midnight Optional Goods"             -- from AutoOpenContainers
ns.items[255686] = "Huge Bag of Midnight Alchemy Goods"              -- from AutoOpenContainers
ns.items[255684] = "Huge Bag of Midnight Leatherworking Goods"       -- from AutoOpenContainers
ns.items[255683] = "Huge Bag of Midnight Jewelcrafting Goods"        -- from AutoOpenContainers
ns.items[255682] = "Huge Bag of Midnight Skins"                      -- from AutoOpenContainers
ns.items[255679] = "Huge Bag of Midnight Minerals"                   -- from AutoOpenContainers
ns.items[255678] = "Huge Bag of Midnight Herbs"                      -- from AutoOpenContainers
ns.items[255666] = "Huge Bag of Midnight General Goods"              -- from AutoOpenContainers
ns.items[255428] = "Tolbani's Medicine Satchel"                      -- from AutoOpenContainers
ns.items[254677] = "Apex Cache"                                      -- from AutoOpenContainers
ns.items[254110] = "Weathered Twilight Footlocker"                   -- Random event loot
ns.items[254105] = "Twilight Cultist's Supply Crate"                 -- Event currency and consumables
ns.items[254101] = "Ascension Arrestor's Cache"                      -- Catch-up gear container
ns.items[251970] = "Overflowing Amani Trove"                         -- from AutoOpenContainers
ns.items[251327] = "Thalassian Tailor's Tote Bag"                    -- from AutoOpenContainers
ns.items[251326] = "Thalassian Enchanter's Purse"                    -- from AutoOpenContainers
ns.items[251324] = "Basket of Eversong Herbs"                        -- from AutoOpenContainers
ns.items[251322] = "Thalassian Leatherworker's Duffel"               -- from AutoOpenContainers
ns.items[251321] = "Collection of Eversong Minerals"                 -- from AutoOpenContainers
ns.items[251287] = "Generous Bundle of Petrified Roots"              -- from AutoOpenContainers
ns.items[251286] = "Bundle of Petrified Roots"                       -- from AutoOpenContainers
ns.items[250975] = "Hellcaller Chest"                                -- from OpenableBeGone
ns.items[250755] = "Pouch of Mystic Grindings"                       -- from AutoOpenContainers
ns.items[250754] = "Bag of Wild Skinnings"                           -- from AutoOpenContainers
ns.items[250753] = "Bag of Cracked Orebits"                          -- from AutoOpenContainers
ns.items[250750] = "Pouch of Sprouted Clippings"                     -- from AutoOpenContainers
ns.items[250117] = "Cache of Quel'Thalas Treasures"                  -- from AutoOpenContainers
ns.items[250116] = "Cache of Quel'Thalas Treasures"                  -- from AutoOpenContainers
ns.items[246585] = "Artisan's Consortium Payout"                     -- from AutoOpenContainers
ns.items[245651] = "Bouquet of Herbs"                                -- from AutoOpenContainers
ns.items[245650] = "Bouquet of Herbs"                                -- from AutoOpenContainers
ns.items[245648] = "School of Gems"                                  -- from AutoOpenContainers
ns.items[245647] = "School of Gems"                                  -- from AutoOpenContainers
ns.items[245644] = "Box of Rocks"                                    -- from AutoOpenContainers
ns.items[242650] = "Box of Rocks"                                    -- from AutoOpenContainers
ns.items[241138] = "Harandar Peridot Prism"                          -- from AutoOpenContainers
ns.items[241137] = "Harandar Peridot Prism"                          -- from AutoOpenContainers
ns.items[241136] = "Sanguine Garnet Prism"                           -- from AutoOpenContainers
ns.items[241135] = "Sanguine Garnet Prism"                           -- from AutoOpenContainers
ns.items[241134] = "Tenebrous Amethyst Prism"                        -- from AutoOpenContainers
ns.items[241133] = "Tenebrous Amethyst Prism"                        -- from AutoOpenContainers
ns.items[241132] = "Amani Lapis Prism"                               -- from AutoOpenContainers
ns.items[241131] = "Amani Lapis Prism"                               -- from AutoOpenContainers
ns.items[239077] = "Mound of Mildly-Meaningful Meat"                 -- from AutoOpenContainers
ns.items[238531] = "Radiant Stomach"                                 -- from AutoOpenContainers
ns.items[225100] = "Overflowing Abundant Satchel"                    -- High-threshold event reward
ns.items[224784] = "Pinnacle Cache"                                  -- Weekly world event reward

